### PR TITLE
Paket upgrade

### PR DESCRIPTION
**Pull request by smoothdeveloper**
- migrated from raw NuGet to paket
- updated depedencies

### CODE REVIEW

**Comment by gbaydin** [comment]
Dear Gauthier (if I may),

Thank you very much for this pull request, and I'm sorry for the delay in responding.

I am currently working on a significant rewrite of DiffSharp and I want it to use .NET Core. I've been waiting for the dust to settle down (regarding F# support and tooling in .NET Core) for making the updates.

I understand that your request is for paket support. I am not really familiar with the choice of paket vs nuget. Can't they work together? My understanding was that paket could fetch the nuget package of DiffSharp or also fetch DiffSharp from this git repository. Could you please explain me the limitation this pull request is fixing?

The Appveyor build seems to be failing because it can't locate FSharp.Quotations.Evaluator.

**Comment by smoothdeveloper** [comment]
Dear Atilim ( :smile:  )

The main aspect of using paket in this repository is to ease the current maintenance of dependencies, for example when you want to update your dependencies, you need to:

* change packages.config (whichever way but it is not as nice as calling `.paket\paket.exe update`
* update the documentation files (if FSharp.Formatting version is updated, you'll need to point to correct folder, this is not to be done if we use paket)
* additional changes to the project files are coming
* maintain manually binding redirects

I'm not listing things paket makes easier but major pain points of nuget.

paket works well with nuget, it is a better nuget client than nuget.exe itself and is used in most fsharp projects but also in growing number of .net projects because it just remove lots of pain from using nuget.exe (or VS GUI for nuget).

For users of DiffSharp, they can use nuget or paket, this PR won't affect users using the package from nuget.org.

Now if we want to use paket (for .net framework but support for .net core will be coming in due time) it is just convenience as described above and doesn't hinder us to add .net core support AFAIK; if you have changes coming I'd be happy to rebase that PR on top of it.

Regarding Appveyor I still need to look at what needs to be done so packages are restored like it was done with nuget before, I'll update my PR shortly and we can check if it passes that stage.

**Comment by dsyme** [comment]
@gbaydin I'm hopeful this library could be a .NET Standard 1.x library, portable between .NET Core and .NET Framework. It may depend on your dependencies though.  Let's take a look when you move to that. 

I think Paket is a good choice for this repo. Paket is/wil be usable for such libraries.

**Comment by gbaydin** [comment]
@dsyme, I really want this to be a .NET Standard library too. I've been reading through most the documentations here:

https://docs.microsoft.com/en-us/dotnet/articles/core/tutorials/libraries

I've been working on a version which targets .NET Framework 4.5 and .NET Standard 1.6, with something like:

```json
{
    "version": "0.7.8-*",
    "buildOptions": {
        "compilerName": "fsc",
        "compile": {
            "includeFiles": [
                "Util.fs",
                "Backend.fs",
                "Backend.OpenBLAS.fs",
                "Config.fs",
                "AD.Float32.fs",
                "AD.Float64.fs"
            ]
        }
    },
    "tools": {
        "dotnet-compile-fsc": {
            "version": "1.0.0-preview2-*"
        }
    },
    "frameworks": {
        "netstandard1.6": {
            "dependencies": {
                "NETStandard.Library": "1.6.0",
                "Microsoft.FSharp.Core.netcore": "1.0.0-alpha-160629"
            }
        },
        "net45":{
            "dependencies": {
                "FSharp.Core" : "4.0.0.1"
            }
        }
    }
}
```

This compiles successfully with .NET Core 1.0.0-preview2-003121 on Ubuntu 16.04, which is good. :)

As I understand, I can't target any .NET Standard lower than 1.6 because I get, for example: 

```
Package Microsoft.FSharp.Core.netcore 1.0.0-alpha-160629 is not compatible with netstandard1.2 (.NETStandard,Version=v1.2). Package Microsoft.FSharp.Core.netcore 1.0.0-alpha-160629 supports: netstandard1.6 (.NETStandard,Version=v1.6)
```

One of my issues is getting the dependency "FSharp.Quotations.Evaluator" working with netstandard1.6. It seems to support it through a portable profile (https://www.nuget.org/packages/FSharp.Quotations.Evaluator/), and I have to read a bit more to understand how to get it working.

The biggest showstopper for me is when I could not load and use the DiffSharp.dll compiled for netstandard1.6, in F# Interactive:

```
F# Interactive for F# 4.0 (Open Source Edition)
Freely distributed under the Apache 2.0 Open Source License

For help type #help;;

> #r "DiffSharp.dll";;

  #r "DiffSharp.dll";;
  ^^^^^^^^^^^^^^^^^^

/home/gunes/DiffSharp-core/src/DiffSharp/bin/Debug/netstandard1.6/stdin(1,1): error FS0078: Unable to find the file 'System.Runtime.dll' in any of
 /usr/lib/mono/4.5
 /home/gunes/DiffSharp-core/src/DiffSharp/bin/Debug/netstandard1.6
 /usr/lib/cli/fsharp/
```

My understanding is that the version of F# Interactive I have (installed following the instructions here: http://fsharp.org/use/linux/ ) does not support .NET Core libraries, because it is using mono. This usage case is very important for us, because we want to be able to direct the users to install the new, shiny, cross-platform .NET Core, and use F# Interactive and .fsx files to run their experiments with DiffSharp.

I really hope that we could have instructions on fsharp.org to get the F# tools using .NET Core.

**Comment by gbaydin** [comment]
Following from my previous message:

Or, is the issue I'm having with F# Interactive just about pointing it to the correct path for the dependencies that are restored through "dotnet restore"?

**Comment by dsyme** [comment]
> The biggest showstopper for me is when I could not load and use the DiffSharp.dll compiled for netstandard1.6, in F# Interactive:

Please record this bug at http://github.com/fsharp/fsharp.  It is crucial we solve it and give good workarounds.  You may be able to workaround by finding System.Runtime.dll in the Mono installation and referencing it explicitly, or by a relative path

**Comment by gbaydin** [comment]
Of course, I will report it.

**Comment by gbaydin** [comment]
@dsyme, I reported the bug here: https://github.com/fsharp/fsharp/issues/584

**Comment by zgrkpnr** [comment]
@gbaydin Sorry for the interference. If possible, please don't add extra dependencies and requirements for tweaking some configurations and such. It is an awesome library and it is perfectly ready to use (unlike linux guys, we prefer plug 'n play type of libraries). Again, I apologize for my rant. Don't mind me.

**Comment by smoothdeveloper** [comment]
@zgrkpnr if you refer to paket, this doesn't add any dependency, it is only for maintenance of this repository but won't impact the consumers of the NuGet package in any way.

Am I understanding correctly your use case or you are talking about building DiffSharp on your own?

**Comment by smoothdeveloper** [comment]
@gbaydin I've updated this PR, now it also runs the nunit tests on appveyor (I'm not sure but I think current master doesn't do that).

Later we should think about a FAKE script because doing what I do in build.cmd is not greatest option and will not work on other platforms.

@zgrkpnr could you detail your concerns because I'm not clear if they are as a consumer of nuget package (no change in this case) or as someone building this repository (in which case paket and an eventual FAKE script would help and give better out of box experience just by running build.cmd IMHO).

Thanks!

**Comment by dsyme** [comment]
@zgrkpnr A couple of things

* It would be great to have a testimonial for your use of the library added to the docs.  If you are at an enterprise where you can't give details, then just submit a private testimonial without revealing details.

* It would be awesome to have more contributors to the library, especially in areas orthogonal to @gbaydin's amazing work - e.g. refining perf here and there, adding more samples

* Any help in spreading the word about this great library into the communities that could benefit from it would be awesome!

**Comment by zgrkpnr** [comment]
@dsyme I am using personally. I am actually trying to create extentions for [Hype](https://github.com/hypelib/Hype) such as RBM, Autoencoders and such, using DiffSharp. I was planning to make a pull request (not for Diffsharp, because AD is well beyond my skills) to Hype library when I finish everything and do some tests. 

If @gbaydin makes a mailing list about near future plans, maybe it would be helpful for preventing us to do replicated things unknowingly. 
 
Thus, whether or not I will be able to contribute to Hype, my testimonial will be those machine learning extensions.

**Comment by smoothdeveloper** [comment]
@zgrkpnr fsharp-data-science@googlegroups.com might be good place to discuss those topics.

**Comment by gbaydin** [comment]
@smoothdeveloper, @zgrkpnr, I'm currently traveling and I haven't had an opportunity to answer your latest messages and merge the pull requests. I will be back next week. Having a mailing list about future plans is a great idea! We also have a gitter chat room that has a nice integration with GitHub.

**Comment by zgrkpnr** [comment]
@smoothdeveloper I am sorry I didn't see your second message. I am absolutely talking about nuget package, hence my thumbs up=)

**Comment by smoothdeveloper** [comment]
@gbaydin any chance to get this merged?

**Comment by dsyme** [comment]
@gbaydin Perhaps consider making @smoothdeveloper a co-maintainer for the repo?

**Comment by gbaydin** [comment]
@smoothdeveloper, @dsyme, apologies for being unresponsive for so long. 

This is mainly for two reasons:
- my job change somewhat disrupted my work on DiffSharp
- I am basically rewriting this library from scratch for the third time for version 0.8.0, using .NET Core, with CUDA and OpenCL support, getting rid of the "D, DV, DM" types in favor of a general "Tensor" type and going through a very long list of missing features. (It's taking time and this work is currently in a private repo.) I'm really interested in using just a regular "dotnet restore" instead of Paket.

I don't personally use or like Paket, but if this helps others' workflow, I think the best thing to do is to merge this in the meantime. I'm not sure if I will use Paket with the .NET Core release of DiffSharp. I am happy with just using the standard package manager of the .NET CLI tools. I expect the .netstandard version to have no dependencies.

**Comment by dsyme** [comment]
@gbaydin OK, super, thanks for the update!!  Great to know your plans, please let us know if we can help

**Comment by smoothdeveloper** [comment]
Just in context of current paket usage

* it does really help with regard to binding redirects (especially with fsharp.core) as well as upgrading/managing packages consistently, IIRC the working copy wouldn't work out of the box also
* it helps with reducing amount of change in script files (see version numbers that creeps in `#load` directives) and project files

I can't talk for dotnetcore yet, but paket is eventually expected to integrate with `dotnet restore` I think the team at MS stated that they were looking into not "getthoizing" other solutions and leave hooks for proper integration.

I understand concern with "vanilla" tools versus "custom" tools, it just happens that "vanilla" in historical context of nuget has unhandy defaults, this is most probably better in dotnetcore / future release of nuget client.

Having new version of DiffSharp with those backends you mention sounds awesome!

**Comment by gbaydin** [comment]
Thank you very much for all this information, it seems that I should learn more about Paket.
